### ISSUE TITLE
botのここやっぱりいい感じにしたい 

### ISSUE THREAD

**Issue by nullnyat** [nullnyat/nca10.net#4]
![image](https://user-images.githubusercontent.com/89781396/153149486-f8a4f620-ed33-4275-ab41-0b4b6fe5b471.png)
できそうならbotなアカウント名の色を青とかにするとか

**Comment by sim1222** [comment]
みつけた
https://github.com/NullCatSlave/nca10.net/blob/c57f03b092a01f37a9649b8db931576e6d89de12/packages/client/src/components/note-header.vue#L6
![image](https://user-images.githubusercontent.com/50144466/153222719-536196de-84d8-49d9-b436-77934872c375.png)

**Comment by nullnyat** [comment]
ok
